/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{html,ts}"],
    theme: {
        screens: {
            sm: "480px",
            md: "768px",
            lg: "976px",
            xl: "1440px",
        },
        colors: {
            blue: "#1fb6ff",
            purple: "#7e5bef",
            pink: "#ff49db",
            orange: "#ff7849",
            green: "#13ce66",
            yellow: "#ffc82c",
            "gray-dark": "#273444",
            gray: "#8492a6",
            "gray-light": "#d3dce6",
            primary: "#DC0A2D",
            white: "#FFFFFF",
            "pokemon-type-bug": "#A7B723",
            "pokemon-type-dark": "#75574C",
            "pokemon-type-dragon": "#7037FF",
            "pokemon-type-electric": "#F9CF30",
            "pokemon-type-fairy": "#E69EAC",
            "pokemon-type-fighting": "#C12239",
            "pokemon-type-fire": "#F57D31",
            "pokemon-type-flying": "#A891EC",
            "pokemon-type-ghost": "#70559B",
            "pokemon-type-normal": "#AAA67F",
            "pokemon-type-grass": "#74CB48",
            "pokemon-type-ground": "#DEC16B",
            "pokemon-type-ice": "#9AD6DF",
            "pokemon-type-poison": "#A43E9E",
            "pokemon-type-psychic": "#FB5584",
            "pokemon-type-rock": "#B69E31",
            "pokemon-type-steel": "#B7B9D0",
            "pokemon-type-water": "#6493EB",
        },
        fontFamily: {
            poppins: ["Poppins", "sans-serif"],
        },
        extend: {},
    },
    plugins: [],
};
